Fix playlist navigation
sugarlabs/jukebox-activity pull request #31
Opened 2020-07-08 16:17 UTC by shaansubbaiah

Clicking the move-up and move-down buttons when there were no songs in 
the playlist above or below the selected song, threw errors.
This fix moves the song only if another song exists at the position it is
to be moved into.
 
Traceback:
Clicking MOVE UP when there's no song above:
```
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Jukebox.activity/activity.py", line 201, in _move_down_cb
    self.playlist_widget.move_down()
  File "/usr/share/sugar/activities/Jukebox.activity/playlist.py", line 111, in move_down
    position = self.treemodel.get_iter(
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 869, in get_iter
    raise ValueError("invalid tree path '%s'" % path)
ValueError: invalid tree path '1'

```
Clicking MOVE DOWN when there's no song below:
```
(sugar-activity3:1768): Gtk-WARNING **: 15:55:15.881: ../../../../gtk/gtktreemodel.c:646:
Negative numbers in path -1 passed to gtk_tree_path_new_from_string
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1206, in __new__
    return TreePath.new_from_string(path)
TypeError: constructor returned NULL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/sugar/activities/Jukebox.activity/activity.py", line 198, in _move_up_cb
    self.playlist_widget.move_up()
  File "/usr/share/sugar/activities/Jukebox.activity/playlist.py", line 96, in move_up
    position = self.treemodel.get_iter(
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 866, in get_iter
    path = self._coerce_path(path)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 841, in _coerce_path
    return TreePath(path)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1208, in __new__
    raise TypeError("could not parse subscript '%s' as a tree path" % path)
TypeError: could not parse subscript '-1' as a tree path
```

Fixes #30

2020-07-09 04:46 UTC, shaansubbaiah commented
@quozl @chimosky @srevinsaju, please review.

2020-07-09 06:55 UTC, quozl commented
Thanks.  Reviewed.  Would the patch be smaller and therefore easier to understand if an early return was used along with an inverted complex conditional expression?  (asking also to make sure I didn't miss another change in the patch).

2020-07-09 07:07 UTC, shaansubbaiah commented
Yes, I'll update the commit 👍

2020-07-09 07:41 UTC, shaansubbaiah commented
Updated, with changes as suggested.

2020-07-09 18:33 UTC, srevinsaju requested changes
Great! Tested works fine. Your new changes L96-101 and L117-122 brings some new `flake8` warnings

```bash
./playlist.py:100:21: E117 over-indented
./playlist.py:121:21: E117 over-indented
```
I guess you will have to shift it a bit behind to remove `E117`.

2020-07-10 04:53 UTC, quozl commented
Looks good, thanks.  I agree indentation can improve.

The patch in this form also reveals how the assignment to `position` looks remarkably similar to the code in the new conditional test, but uses `+ 1` or `- 1`, probably because that's what was available back then.

Would it be better to have something like this;

```python
    def move_up(self):
        selected_iter = self.selection.get_selected()[1]
        if selected_iter is None:
            return

        position = self.treemodel.iter_previous(
            self.treemodel.get_iter(
                int(str(self.treemodel.get_path(selected_iter)))))
        if position is None:
            return

        self.treemodel.move_before(selected_iter, position)
        ...
```

Untested.

2020-07-10 05:51 UTC, shaansubbaiah commented
@quozl that worked, I had to use get_iter() instead of the int(str()) around the treepath for iter_previous() and iter_next() to work.

2020-07-10 05:57 UTC, shaansubbaiah commented
Also the empty `L108 in move_up()` was added as there's an empty line `L117 in move_down()` for uniformity, do I remove it?

2020-07-10 06:19 UTC, quozl commented
Thanks.  Looks more beautiful now.  Reviewed.  Approved.  I'm fine with the blank line added.  Occasional blank lines increase comprehension by new readers.

2020-07-15 15:09 UTC, chimosky commented
Reviewed, thanks.

2020-07-15 15:09 UTC, merged